# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_card', models.CharField(blank=True, default=b'', max_length=500)),
                ('word_set', models.CharField(blank=True, default=b'', max_length=1000)),
                ('channel_id', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=30)),
                ('team_color', models.CharField(max_length=4)),
                ('is_spy_master', models.BooleanField(default=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
            ],
        ),
    ]
