# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_master',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='slack_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_color',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
