# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170115_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accepting_new_players',
            field=models.BooleanField(default=True),
        ),
    ]
