# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_game_accepting_new_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_spy_master',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
    ]
