# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170115_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
    ]
