# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170116_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_team_playing',
            field=models.CharField(blank=True, default=b'', max_length=4),
        ),
    ]
