# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_current_team_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_guesses_left',
            field=models.IntegerField(default=0),
        ),
    ]
