# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game_num_guesses_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revealed_cards',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
