# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_game_revealed_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='revealed_cards',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
    ]
