# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-22 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170127_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AlterField(
            model_name='game',
            name='revealed_cards',
            field=models.CharField(blank=True, default=b'[]', max_length=500),
        ),
    ]
